Eval command output to privatebin
Snaacky/chiya pull request #94
Opened 2021-09-01 09:50 UTC by R3D4CTED

Longer command outputs and errors, exceeding 512 characters will be uploaded to privatebin, to prevent the "Form Length Exceeded" errors when making the embed.

2021-09-07 23:03 UTC, Snaacky requested changes

2021-09-07 23:03 UTC, Snaacky commented on cogs/commands/moderation/administration.py
> +    def upload_to_privatebin(self, payload: str) -> str:
Payload is a non-descriptive variable name.

2021-09-07 23:03 UTC, Snaacky commented on cogs/commands/moderation/administration.py
> +            return privatebinapi.send("https://bin.piracy.moe", text=payload, expiration='never', burn_after_reading=True)["full_url"]
This shouldn't be set to burn on read. It would be nice if the Privatebin was stored as a variable instead of hardcoded.

2021-09-07 23:03 UTC, Snaacky commented on cogs/commands/moderation/administration.py
> +        except:
Don't use a generic except.

2021-09-07 23:03 UTC, Snaacky commented on cogs/commands/moderation/administration.py
> +            return "Error uploading to privatebin. Is privatebin up?"
Just return false here.

2021-09-07 23:06 UTC, lunarmint commented on cogs/commands/moderation/administration.py
> +            return privatebinapi.send("https://bin.piracy.moe", text=payload, expiration='never', burn_after_reading=True)["full_url"]
Agreed on this, try-except is known to have high cost, I'd say try to avoid using it unless absolutely necessary, and a variable would also make it looks cleaner (less indent).

2021-09-08 09:10 UTC, lunarmint commented on cogs/commands/moderation/administration.py
> +        return "​"
Would it be a bit cleaner this way?
```
        uploaded_info = privatebinapi.send("https://bin.piracy.moe", text=text_to_be_uploaded, expiration='never')['full_url']
        # returning a zero width whitespace character
        if not uploaded_info:
            return "​"
```

2021-09-24 03:30 UTC, R3D4CTED commented on cogs/commands/moderation/administration.py
> +        return "​"
Snaacky wanted me to store in a variable and then do it.

2022-07-31 18:48 UTC, Snaacky commented
Closing as this hasn't been touched in a year.

2022-07-31 18:48 UTC, closed without merging